BEGIN;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100)  NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  mobile VARCHAR(255),
  password TEXT NOT NULL,
  created_at TEXT DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'DD/MM/YYYY HH12:MI:SS:MS:US AM')
);

COMMIT;


